export const currencies = [
  { key: "USD", name: "United States dollar", symbol: "$" },
  { key: "EUR", name: "Euro", symbol: "€" },
  { key: "JPY", name: "Japanese yen", symbol: "¥" },
  { key: "GBP", name: "British pound sterling", symbol: "£" },
  { key: "AUD", name: "Australian dollar", symbol: "A$" },
  { key: "CAD", name: "Canadian dollar", symbol: "C$" },
  { key: "CHF", name: "Swiss franc", symbol: "CHF" },
  { key: "CNY", name: "Chinese yuan", symbol: "¥" },
  { key: "SEK", name: "Swedish krona", symbol: "kr" },
  { key: "NZD", name: "New Zealand dollar", symbol: "NZ$" },
  { key: "MXN", name: "Mexican peso", symbol: "$" },
  { key: "SGD", name: "Singapore dollar", symbol: "S$" },
  { key: "HKD", name: "Hong Kong dollar", symbol: "HK$" },
  { key: "NOK", name: "Norwegian krone", symbol: "kr" },
  { key: "KRW", name: "South Korean won", symbol: "₩" },
  { key: "TRY", name: "Turkish lira", symbol: "₺" },
  { key: "INR", name: "Indian rupee", symbol: "₹" },
  { key: "RUB", name: "Russian ruble", symbol: "₽" },
  { key: "BRL", name: "Brazilian real", symbol: "R$" },
  { key: "ZAR", name: "South African rand", symbol: "R" },
  { key: "XOF", name: "West African CFA franc", symbol: "FR" },
  { key: "XAF", name: "Central African CFA franc", symbol: "FR" },
  { key: "SAR", name: "Saudi riyal", symbol: "﷼" },
  { key: "AED", name: "United Arab Emirates dirham", symbol: "د.إ" },
  { key: "MYR", name: "Malaysian ringgit", symbol: "RM" },
  { key: "PHP", name: "Philippine peso", symbol: "₱" },
  { key: "IDR", name: "Indonesian rupiah", symbol: "Rp" },
  { key: "THB", name: "Thai baht", symbol: "฿" },
];
